[package]
name = "api"
version = "0.1.0"
authors = ["Pradip Caulagi <caulagi@gmail.com>"]
description = "Api's for ishakuni"

[dependencies]
actix-web = "0.7.19"
env_logger = "0.5.10"
actix = "0.7.9"
