[package]
name = "api"
version = "0.1.0"
authors = ["Pradip Caulagi <caulagi@gmail.com>"]
description = "Api's for ishakuni"

[dependencies]
bytes = "0.4"
env_logger = "0.5.10"
futures = "0.1"
http = "0.1"
log = "0.4"
prost = "0.5"
serde = { version = "^1.0", features = ["derive"] }
tokio = "0.1.18"
tower = { git = "https://github.com/tower-rs/tower" }
tower-add-origin = { git = "https://github.com/tower-rs/tower-http" }
tower-grpc = { git = "https://github.com/tower-rs/tower-grpc" }
tower-h2 = { git = "https://github.com/tower-rs/tower-h2" }
tower-service = { git = "https://github.com/tower-rs/tower" }
tower-web = { git = "https://github.com/carllerche/tower-web", default-features = false }
